# Generated by Django 3.1.2 on 2020-12-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aptitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1000)),
                ('optionA', models.CharField(max_length=500)),
                ('optionB', models.EmailField(max_length=500)),
                ('optionC', models.CharField(max_length=500)),
                ('optionD', models.CharField(max_length=500)),
                ('correct', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Aptitude',
            },
        ),
        migrations.CreateModel(
            name='Finalresults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('div', models.CharField(max_length=100)),
                ('strtime', models.CharField(max_length=100)),
                ('endtime', models.CharField(max_length=100)),
                ('marks', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Finalresults',
            },
        ),
        migrations.CreateModel(
            name='Listquestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=50)),
                ('Question', models.CharField(max_length=1000)),
                ('optionA', models.CharField(max_length=500)),
                ('optionB', models.EmailField(max_length=500)),
                ('optionC', models.CharField(max_length=500)),
                ('optionD', models.CharField(max_length=500)),
                ('correct', models.CharField(default='A', max_length=500)),
                ('qtype', models.CharField(default='apti', max_length=100)),
            ],
            options={
                'db_table': 'Listquestions',
            },
        ),
        migrations.CreateModel(
            name='quizattempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
            ],
            options={
                'db_table': 'quizattempt',
            },
        ),
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=1000)),
                ('optionA', models.CharField(max_length=500)),
                ('optionB', models.EmailField(max_length=500)),
                ('optionC', models.CharField(max_length=500)),
                ('optionD', models.CharField(max_length=500)),
                ('correct', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Technical',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=30)),
                ('re_password', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=40)),
                ('HSC', models.CharField(max_length=100)),
                ('marks1', models.CharField(max_length=100)),
                ('SSC', models.CharField(max_length=100)),
                ('marks2', models.CharField(max_length=100)),
                ('graduation', models.CharField(max_length=100)),
                ('marks3', models.CharField(max_length=100)),
                ('post_graduation', models.CharField(max_length=100)),
                ('marks4', models.CharField(max_length=100)),
                ('certification', models.CharField(max_length=100)),
                ('company1', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('company2', models.CharField(max_length=100)),
                ('box1', models.CharField(max_length=100)),
                ('box2', models.CharField(max_length=100)),
                ('Salary1', models.CharField(max_length=100)),
                ('Salary2', models.CharField(max_length=100)),
                ('skills', models.CharField(max_length=100)),
                ('Accomplishment', models.CharField(max_length=100)),
                ('Hobby', models.CharField(max_length=100)),
                ('References', models.CharField(max_length=100)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('Languages', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
